site_name: My Docs
theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode